name: Docker Build and Push
on:
  push:
    branches:
      - development
      - staging
      - production
    tags:
    - '*'
    
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    environment: dmh_development
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR: testecr
          REPO: testrepo
          CUSTOM_TAG: "dmh-frontend-" # custom tag
          BRANCH_NAME: ${{ github.ref_name }} # Branch name
          # IMAGE_TAG: $CUSTOM_TAG$BRANCH_NAME
          # IMAGE_TAG="dmh-frontend-$BRANCH_NAME"
          
        run: |
          IMAGE_TAG="dmh-frontend-$BRANCH_NAME"
          docker build -t $ECR/$REPO:$IMAGE_TAG .
          docker images
          echo $ECR/$REPO:$IMAGE_TAG
